#!/usr/bin/env node
/*
 * design-system — regenerate tokens/fonts-inline.css
 *
 * Reads every FFF Acid Grotesk .otf in ../fonts/, base64-encodes it,
 * and writes a single self-contained CSS file at ../tokens/fonts-inline.css
 * with all @font-face rules pre-inlined as data: URIs.
 *
 * Run this whenever the font binaries in ../fonts/ change. The output is
 * checked in so consumers (skills, templates, ad-hoc HTML) can paste the
 * file's contents into a <style> block to get a fully self-contained
 * artifact — no external font deps.
 *
 * Usage:
 *   node "${CLAUDE_PLUGIN_ROOT}/skills/design-system/scripts/regenerate_fonts_inline.js"
 *
 * The script resolves paths relative to its own location, so it works
 * from any working directory.
 */

const fs = require('fs');
const path = require('path');

const FAMILY = 'FFF Acid Grotesk';

// Acid Grotesk weight axis, mapped to match Figma's numeric weights so a
// template asking for `350` (Book) resolves to the Book face — not a snapped
// neighbour. Book sits at 350 and Regular at 400 so both land as exact matches;
// nothing between Light (300) and Medium (500) snaps. The old mapping placed
// Book at 400 (so 350 dropped to 300 Light) and exiled Regular to a separate
// family — see the design-system font-weight fix.
const WEIGHTS = [
  { file: 'FFF-AcidGrotesk-ExtraLight.otf',       weight: 200, style: 'normal' },
  { file: 'FFF-AcidGrotesk-ExtraLightItalic.otf', weight: 200, style: 'italic' },
  { file: 'FFF-AcidGrotesk-Light.otf',            weight: 300, style: 'normal' },
  { file: 'FFF-AcidGrotesk-LightItalic.otf',      weight: 300, style: 'italic' },
  { file: 'FFF-AcidGrotesk-Book.otf',             weight: 350, style: 'normal' },
  { file: 'FFF-AcidGrotesk-BookItalic.otf',       weight: 350, style: 'italic' },
  { file: 'FFF-AcidGrotesk-Regular.otf',          weight: 400, style: 'normal' },
  { file: 'FFF-AcidGrotesk-RegularItalic.otf',    weight: 400, style: 'italic' },
  { file: 'FFF-AcidGrotesk-Medium.otf',           weight: 500, style: 'normal' },
  { file: 'FFF-AcidGrotesk-MediumItalic.otf',     weight: 500, style: 'italic' },
  { file: 'FFF-AcidGrotesk-Bold.otf',             weight: 700, style: 'normal' },
  { file: 'FFF-AcidGrotesk-BoldItalic.otf',       weight: 700, style: 'italic' },
  { file: 'FFF-AcidGrotesk-ExtraBold.otf',        weight: 800, style: 'normal' },
  { file: 'FFF-AcidGrotesk-ExtraBoldItalic.otf',  weight: 800, style: 'italic' },
];

const JETBRAINS_MONO_FAMILY = 'JetBrains Mono';
const JETBRAINS_MONO_WEIGHTS = [
  { file: 'JetBrainsMono-Regular.ttf', weight: 400, style: 'normal', format: 'truetype', mime: 'font/ttf' },
];

function encode(fontsDir, file) {
  const p = path.join(fontsDir, file);
  if (!fs.existsSync(p)) {
    throw new Error(`Missing font file: ${p}`);
  }
  return fs.readFileSync(p).toString('base64');
}

function buildFace(family, file, weight, style, base64, opts = {}) {
  const mime = opts.mime || 'font/otf';
  const format = opts.format || 'opentype';
  return `@font-face {
  font-family: '${family}';
  font-weight: ${weight};
  font-style: ${style};
  font-display: block;
  src: url(data:${mime};base64,${base64}) format('${format}');
}`;
}

function header(scope) {
  return `/* =========================================================================
   FFF Acid Grotesk — base64-inlined @font-face rules (${scope})
   Generated by hx-marketing/skills/design-system/scripts/regenerate_fonts_inline.js
   Source: hx-marketing/skills/design-system/fonts/*.otf
   Regenerate: node "\${CLAUDE_PLUGIN_ROOT}/skills/design-system/scripts/regenerate_fonts_inline.js"

   Paste the contents of this file into a <style> block to render Acid Grotesk
   without any external font dependency. Output HTML is fully self-contained.
   ========================================================================= */
`;
}

function writeBundle({ outFile, fontsDir, faces, monoFaces, scope }) {
  const blocks = [];
  for (const { file, weight, style } of faces) {
    const b64 = encode(fontsDir, file);
    blocks.push(buildFace(FAMILY, file, weight, style, b64));
  }
  for (const { file, weight, style, format, mime } of monoFaces || []) {
    const b64 = encode(fontsDir, file);
    blocks.push(buildFace(JETBRAINS_MONO_FAMILY, file, weight, style, b64, { format, mime }));
  }
  const css = header(scope) + '\n' + blocks.join('\n\n') + '\n';
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, css);
  const sizeKB = Math.round(css.length / 1024);
  console.log(`wrote ${outFile} (${sizeKB} KB, ${blocks.length} @font-face rules)`);
}

function main() {
  const here = __dirname;
  const fontsDir = path.resolve(here, '..', 'fonts');
  const tokensDir = path.resolve(here, '..', 'tokens');

  if (!fs.existsSync(fontsDir)) {
    console.error(`Fonts directory not found: ${fontsDir}`);
    process.exit(2);
  }

  writeBundle({
    outFile: path.join(tokensDir, 'fonts-inline.css'),
    fontsDir,
    faces: WEIGHTS,
    monoFaces: JETBRAINS_MONO_WEIGHTS,
    scope: 'full family — all 14 weights/styles + JetBrains Mono Regular',
  });

  const cardSubset = WEIGHTS.filter(
    (w) => w.style === 'normal' && [300, 350, 400, 500].includes(w.weight),
  );
  writeBundle({
    outFile: path.join(tokensDir, 'fonts-inline-card.css'),
    fontsDir,
    faces: cardSubset,
    monoFaces: JETBRAINS_MONO_WEIGHTS,
    scope: 'card subset — Light/Book/Regular/Medium upright + JetBrains Mono Regular',
  });
}

main();
